---
- hosts: localhost
  tasks:
  - yum:
     state: present
     name: "{{item}}"
    with_items:
    - java
    - "./{{dist}}/kafka-{{kafka_version}}.{{arch}}.rpm"

  - template:
     src: zookeeper.service
     dest: /etc/systemd/system/zookeeper.service
     
  - service:
     name: zookeeper
     enabled: yes
     state: started 
  
  - template:
     src: kafka.service
     dest: /etc/systemd/system/kafka.service
  
  - service:
     name: kafka
     enabled: yes
     state: started 
