#!/bin/bash

KAFKAHOME=/opt/kafka
KAFKABIN=${KAFKAHOME}/bin
KAFKACONF=${KAFKAHOME}/config

daemonize -ae /var/log/zookeeper.error -o /var/log/zookeeper.out \
 -p /var/run/zookeeper -l /var/lock/zookeeper -v \
 ${KAFKABIN}/zookeeper-server-start.sh ${KAFKACONF}/zookeeper.properties

sleep 1

term_handler() {
  echo 'Stopping Kafka....'
  if [ $KAFKA_PID -ne 0 ]; then
    kill -s TERM "$KAFKA_PID"
    wait "$KAFKA_PID"
  fi
  echo 'Kafka stopped.'
  exit
}


# Capture kill requests to stop properly
trap "term_handler" SIGHUP SIGINT SIGTERM
${KAFKABIN}/kafka-server-start.sh ${KAFKACONF}/server.properties &
KAFKA_PID=$!
wait "$KAFKA_PID"

