---
- hosts: localhost
  tasks:
  - stat:
      path: /.dockerenv
    register: stat_docker

  - include: docker.yml
    when: stat_docker.stat.exists

  - include: service.yml
    when: not stat_docker.stat.exists
