version: "2"
services:
  kafka:
    image: centos:7
    ports:
    - "2181:2181"
    - "9092:9092"

    command: ['/docker-cmd']
  #   command: ['/usr/bin/dumb-init', '/usr/sbin/apache2ctl', '-D', 'FOREGROUND']
  #   dev_overrides:
  #     environment:
  #       - "DEBUG=1"
  #
registries:
  docker:
    url: https://hub.docker.com/
    namespace: jmalacho
